version: '3.9'
services:
  db:
    image: mysql:9.3.0
    container_name: eft-db
    environment:
      MYSQL_DATABASE: eft-db
      MYSQL_USER: 
      MYSQL_PASSWORD: MYSQL_ALLOW_EMPTY_PASSWORD
      MYSQL_ROOT_PASSWORD: password123 
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
volumes:
  db_data: