services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eft_api
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - DOCKER_CONTAINER=1
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    env_file:
      - .env
    networks:
      - eft-network

  redis:
    image: redis:7-alpine
    container_name: redis_container
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    command: [
      "redis-server",
      "--requirepass", "${REDIS_PASSWORD}",
      "--save", "",
      "--appendonly", "no"
    ]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - eft-network

  db:
    image: mysql:8.3.0
    container_name: eft-db
    environment:
      MYSQL_DATABASE: eft-db
      MYSQL_USER: eft_user
      MYSQL_PASSWORD: eft_password
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    networks:
      - eft-network

volumes:
  redis_data:
  db_data:

networks:
  eft-network:
