dev:
  DEBUG: true
  DATABASE_URI: "mysql://root:password123@localhost:3307/eft-db"
  TARKOV_DEV_API_URL: "https://api.tarkov.dev/graphql"

stage:
  DEBUG: true
  DATABASE_URI: "mysql://root:password123@localhost:3307/eft-db-stage"
  TARKOV_DEV_API_URL: "https://api.tarkov.dev/graphql"

prod:
  DEBUG: false
  DATABASE_URI: "mysql://root:password123@localhost:3307/eft-db"
  TARKOV_DEV_API_URL: "https://api.tarkov.dev/graphql"
