"""empty message

Revision ID: 809b572d23ff
Revises: 80cb8afd0405
Create Date: 2025-05-16 17:36:54.882658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809b572d23ff'
down_revision = '80cb8afd0405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('icon_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['item_id'])
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['id'])

    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['item_id'])
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('item_id')

    with op.batch_alter_table('icon_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
