"""empty message

Revision ID: 80cb8afd0405
Revises: e1f0d96849a1
Create Date: 2025-05-16 16:27:49.812773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80cb8afd0405'
down_revision = 'e1f0d96849a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icon_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('background_color', sa.String(length=32), nullable=True),
    sa.Column('icon_link', sa.String(length=512), nullable=True),
    sa.Column('grid_image_link', sa.String(length=512), nullable=True),
    sa.Column('base_image_link', sa.String(length=512), nullable=True),
    sa.Column('inspect_image_link', sa.String(length=512), nullable=True),
    sa.Column('image_512_px_link', sa.String(length=512), nullable=True),
    sa.Column('image_8x_link', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('avg_24h_price', sa.Integer(), nullable=True),
    sa.Column('last_low_price', sa.Integer(), nullable=True),
    sa.Column('change_last_48h', sa.Float(), nullable=True),
    sa.Column('change_last_48th_percent', sa.Float(), nullable=True),
    sa.Column('low_24h_price', sa.Integer(), nullable=True),
    sa.Column('high_24h_price', sa.Integer(), nullable=True),
    sa.Column('last_offer_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bsgid', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('normalized_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('base_price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('width', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('wiki_link', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('types', sa.JSON(), nullable=False))
        batch_op.create_unique_constraint(None, ['bsgid'])
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('types')
        batch_op.drop_column('wiki_link')
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('base_price')
        batch_op.drop_column('normalized_name')
        batch_op.drop_column('bsgid')

    op.drop_table('market_data')
    op.drop_table('icon_data')
    # ### end Alembic commands ###
