# id: ID!
# name: String
# normalizedName: String
# shortName: String
# description: String
# basePrice: Int!
# updated: String
# width: Int!
# height: Int!
# backgroundColor: String!
# iconLink: String
# gridImageLink: String
# baseImageLink: String
# inspectImageLink: String
# image512pxLink: String
# image8xLink: String
# wikiLink: String
# types: [ItemType]!
# avg24hPrice: Int
# properties: ItemProperties
# conflictingItems: [Item]
# conflictingSlotIds: [String]
# accuracyModifier: Float
# recoilModifier: Float
# ergonomicsModifier: Float
# hasGrid: Boolean
# blocksHeadphones: Boolean
# link: String
# lastLowPrice: Int
# changeLast48h: Float
# changeLast48hPercent: Float
# low24hPrice: Int
# high24hPrice: Int
# lastOfferCount: Int
# sellFor: [ItemPrice!]
# buyFor: [ItemPrice!]
# containsItems: [ContainedItem]
# category: ItemCategory
# categories: [ItemCategory]!
# bsgCategoryId: String
# handbookCategories: [ItemCategory]!
# weight: Float
# velocity: Float
# loudness: Int
# usedInTasks: [Task]!
# receivedFromTasks: [Task]!
# bartersFor: [Barter]!
# bartersUsing: [Barter]!
# craftsFor: [Craft]!
# craftsUsing: [Craft]!
# historicalPrices: [historicalPricePoint]

# historicalPrices is only available via the item and items queries.
